# Generated docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    image: <image_name>
    ports:
      - "<host_port>:<container_port>"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
