# Test settings for robotics project
project_name: stretch3-robot
output_dir: ../test-output
shell: bash

# Docker specific settings
docker:
  image_name: stretch3
  image_tag: cpu-humble
  registry_username: hrcnthu

# GitHub specific settings
github:
  username: pomelo925
  branches:
    - main
    - dev-pomelo925

# Task-oriented configuration files
config_files:
  readme: config/readme.yml
  docker: config/docker.yml
  license: config/license.yml
  github: config/github.yml

# Features to generate
features:
  - readme
  - license
  - docker
  - github
