# GitHub workflows and repository configuration
# This file contains settings for generating GitHub-related files

# Repository settings
repo_name: my-project
default_branch: main

# Docker workflow configuration
docker_workflow:
  enabled: true
  name: "Docker Build and Push"
  triggers:
    on_push:
      paths:
        - "docker/dockerfile.*"
        - "docker/compose.*.yml"
        - ".github/workflows/docker.*.yml"
    on_manual: true
  
  # Build matrix for different Docker configurations
  matrix:
    cpu:
      dockerfile: "docker/dockerfile.cpu"
      compose_file: "docker/compose.cpu.yml"
      workflow_file: ".github/workflows/docker.cpu.yml"
    gpu:
      dockerfile: "docker/dockerfile.gpu"
      compose_file: "docker/compose.gpu.yml"
      workflow_file: ".github/workflows/docker.gpu.yml"

# Workflow configurations
workflows:
  ci_cd:
    enabled: true
    name: "CI/CD Pipeline"
    triggers:
      - push
      - pull_request
    
  tests:
    enabled: true
    name: "Run Tests"
    node_versions: [16, 18, 20]  # For Node.js projects
    python_versions: ["3.8", "3.9", "3.10", "3.11"]  # For Python projects
    
  security:
    enabled: false
    name: "Security Scan"
    tools:
      - codeql
      - dependency-review

# Issue and PR templates
issue_templates:
  bug_report: true
  feature_request: true
  custom_template: false

pull_request_template: true

# GitHub Pages (if needed)
pages:
  enabled: false
  source_branch: gh-pages
  
# Dependabot configuration
dependabot:
  enabled: true
  schedule: weekly
  ecosystems:
    - npm
    - pip
    - docker
