# Example settings.yml for a ROS robotics project
# Configuration for rtgen repository scaffold generator

project_name: stretch3-robot  # Used for README header and project references
output_dir: ../stretch3-repo  # Relative path from rtgen root where files will be generated
shell: bash   # Default shell for generated scripts: bash, fish, zsh

# Docker specific settings
docker:
  image_name: stretch3  # Docker image name
  image_tag: cpu-humble   # Docker image tag
  registry_username: hrcnthu  # Registry username (e.g., Docker Hub username)

# GitHub specific settings
github:
  username: pomelo925        # GitHub username for workflows
  branches:                  # Branches to trigger workflows
    - main
    - dev-pomelo925

# Task-oriented configuration files
config_files:
  readme: config/readme.yml      # README.md generation settings
  docker: config/docker.yml      # Docker and containerization settings  
  license: config/license.yml    # License file generation settings
  github: config/github.yml      # GitHub workflows and repository settings

# Features to generate (corresponds to config files)
features:
  - readme    # Generate README.md using readme.yml
  - docker    # Generate Docker files using docker.yml  
  - license   # Generate LICENSE using license.yml
  - github    # Generate GitHub workflows using github.yml
